services:
  # XUIBot - User & VLESS Management
  xuibot:
    build:
      context: .
      target: xuibot
    container_name: xuibot
    restart: always
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
      - ./data:/app/data
      - /etc/x-ui:/etc/x-ui:rw  # Доступ к базе данных X-UI
      - ./panels.yaml:/app/panels.yaml:rw  # Конфигурация панелей (read-write для переключения)